<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use App\Models\MobileActivationCode;
use App\Services\TokenService;
use Illuminate\Http\Request;

/**
 * Was completely missing before review: the QR generated by the admin
 * panel encodes app.ministrant.eu/activate/{token}, and the in-app scanner
 * handles that fine by extracting the token from the raw string — but a
 * QR scanned with the phone's normal camera app opens that URL in a
 * browser, and there was no route for it at all (404).
 *
 * This is a deliberately thin fallback page: it does NOT perform
 * activation itself (that still only happens through the app's own
 * check/confirm flow against the JSON API) — it just tells a human what
 * to do next. Deep-linking straight into the app is HTTPS App Links /
 * Universal Links (spec §35) on this exact URL — there is deliberately
 * NO second, custom-scheme mechanism (a dead `ministrantmanager://...`
 * link was removed here per review — no Android/iOS build actually
 * registers that scheme, so it could only ever fail silently or throw an
 * OS-level "no app found" error).
 */
class ActivationLandingController extends Controller
{
    public function show(Request $request, string $token)
    {
        $code = MobileActivationCode::where('token_hash', TokenService::hash($token))->first();

        $parishName = $code && $code->isUsable() ? $code->parish->name : null;

        return view('public.activate', [
            'token' => $token,
            'parishName' => $parishName,
            'valid' => (bool) $parishName,
        ]);
    }
}
