<?php

/**
 * This is NOT a full bootstrap/app.php — it's the snippet to merge into
 * the one generated by `composer create-project laravel/laravel` (Laravel
 * 11's bootstrap/app.php, ->withMiddleware() callback). Laravel 11 has no
 * app/Http/Kernel.php anymore, so middleware aliases are registered here
 * instead.
 *
 * Add this inside the existing ->withMiddleware(function (Middleware
 * $middleware) { ... }) closure:
 */

$middleware->alias([
    'super_admin' => \App\Http\Middleware\EnsureSuperAdmin::class,
]);

// If this is a fresh Laravel 11 install, ->withMiddleware() also needs the
// default 'admin' guard's redirect target for unauthenticated web
// requests configured, e.g.:
//
// $middleware->redirectGuestsTo(fn () => route('admin.login'));
//
// or, if you keep the 'web' guard's default behavior for other routes and
// only want it for the admin group, handle it via the `guest:admin` /
// `auth:admin` middleware already used in routes/web.php (Laravel's
// default Authenticate middleware honors per-guard redirects — see
// Laravel's authentication docs for the exact 11.x syntax, which changed
// from Kernel-based redirectTo() in an application several times during
// active development; verify against whatever 11.x patch version you
// install).
