import 'package:flutter/material.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'dart:io' show Platform;

import 'core/database/app_database.dart';
import 'core/deeplink/deep_link_service.dart';
import 'core/network/api_client.dart';
import 'core/offline/connectivity_probe.dart';
import 'core/offline/local_snapshot_server.dart';
import 'core/offline/offline_page_coordinator.dart';
import 'core/offline/page_resource_downloader.dart';
import 'core/offline/snapshot_capture_service.dart';
import 'core/offline/snapshot_encryptor.dart';
import 'core/offline/snapshot_store.dart';
import 'core/secure/secure_storage_service.dart';
import 'core/sync/sync_engine.dart';
import 'features/activation/activation_screen.dart';
import 'features/activation/activation_service.dart';
import 'features/auth/user_session_service.dart';
import 'features/config/config_service.dart';
import 'features/home/home_screen.dart';
import 'features/preflight/preflight_gate.dart';
import 'features/revocation/revocation_handler.dart';
import 'features/webview/webview_handoff_service.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MinistrantManagerApp());
}

class MinistrantManagerApp extends StatefulWidget {
  const MinistrantManagerApp({super.key});

  @override
  State<MinistrantManagerApp> createState() => _MinistrantManagerAppState();
}

class _MinistrantManagerAppState extends State<MinistrantManagerApp> {
  AppDatabase? _db;
  late final SecureStorageService _secureStorage;
  late final ApiClient _api;
  SyncEngine? _syncEngine;
  ActivationService? _activationService;
  RevocationHandler? _revocationHandler;
  ConfigService? _configService;
  UserSessionService? _userSessionService;
  // P13 fix (found before any physical device test ran): until this
  // round, nothing in the real app ever constructed these — every WebView
  // module tap went straight to LegacyModuleScreen, meaning the entire
  // P2-P10 offline chain was fully built and fully tested but completely
  // UNREACHABLE from the actual app. Rebuilt fresh inside
  // _openFreshDatabaseAndWireServices() every call, same reasoning as
  // _snapshotStore before it: the snapshot encryption key can be deleted/
  // regenerated by RevocationHandler, so these must never be built once
  // and reused across a revoke/reset-triggered rebuild.
  OfflinePageCoordinator? _offlinePageCoordinator;
  final _deepLinkService = DeepLinkService();
  String? _pendingDeepLinkToken;

  bool? _isActivated; // null while checking
  String _appVersion = '1.0.0';
  String _osVersion = '';

  @override
  void initState() {
    super.initState();
    _secureStorage = SecureStorageService();
    _api = ApiClient(_secureStorage);
    _init();
    _deepLinkService.listen((token) {
      // A link can arrive before _init() finishes (cold start) or any
      // time later while already activated (harmless — ActivationScreen
      // isn't shown in that case, the token is just ignored downstream).
      setState(() => _pendingDeepLinkToken = token);
    });
  }

  @override
  void dispose() {
    _deepLinkService.dispose();
    super.dispose();
  }

  Future<void> _init() async {
    // Real "iOS 17.5" / "Android 14" strings — NOT Platform.operatingSystem,
    // which only ever returns the bare "ios"/"android" and would silently
    // clobber the good value the activation flow already sent once the
    // first heartbeat fires.
    final pkgInfo = await PackageInfo.fromPlatform();
    final osVersion = await _resolveOsVersion();
    final activated = await _secureStorage.isActivated;

    await _openFreshDatabaseAndWireServices();

    setState(() {
      _appVersion = pkgInfo.version;
      _osVersion = osVersion;
      _isActivated = activated;
    });
  }

  /// Builds a brand-new AppDatabase (with its encryption key — freshly
  /// generated if none exists, e.g. right after a crypto-erase — see
  /// SecureStorageService.getOrCreateDbEncryptionKey()) and every service
  /// that depends on it. Called once at cold start, and AGAIN after a
  /// revoke-triggered crypto-erase (review round 2, point 2) — the OLD
  /// AppDatabase instance is closed and its file is gone at that point,
  /// so nothing that follows may keep using it.
  Future<void> _openFreshDatabaseAndWireServices() async {
    final dbKey = await _secureStorage.getOrCreateDbEncryptionKey();
    final db = AppDatabase(dbKey);
    // Offline-architecture milestone, P8.2: resolved fresh on every call
    // to this method, exactly like dbKey just above — after a revoke-
    // triggered crypto-erase, RevocationHandler has already deleted the
    // OLD snapshot encryption key, so building this once and reusing it
    // forever would keep using a stale encryptor referencing a key that
    // no longer exists. A purely local variable is enough: nothing
    // outside this method currently needs to read it (both consumers,
    // RevocationHandler and UserSessionService, are constructed right
    // here with it), so there is no state field for it on this class.
    final snapshotKey = await _secureStorage.getOrCreateSnapshotEncryptionKey();
    // One shared instance — SnapshotEncryptor is a stateless wrapper
    // around this one key, so SnapshotStore and LocalSnapshotServer
    // below can safely use the exact same instance rather than two
    // independently-constructed ones that would need to be kept in sync.
    final snapshotEncryptor = SnapshotEncryptor(hexKey: snapshotKey);
    final snapshotStore = SnapshotStore(encryptor: snapshotEncryptor);
    final syncEngine = SyncEngine(db: db, api: _api, secureStorage: _secureStorage);
    final activationService = ActivationService(api: _api, secureStorage: _secureStorage);
    final revocationHandler = RevocationHandler(db: db, secureStorage: _secureStorage, snapshotStore: snapshotStore);
    final configService = ConfigService(db: db, api: _api);
    final userSessionService = UserSessionService(api: _api, secureStorage: _secureStorage, db: db, snapshotStore: snapshotStore);

    // P13 fix: the actual online<->offline WebView chain, built here for
    // the very first time — see this class's own _offlinePageCoordinator
    // field docblock for why it was missing from the real app entirely
    // until now, and why it must be rebuilt fresh on every call to this
    // method, same as snapshotStore above.
    final handoffService = WebviewHandoffService(api: _api, secureStorage: _secureStorage);
    final offlinePageCoordinator = OfflinePageCoordinator(
      connectivityProbe: ConnectivityProbe(),
      captureService: SnapshotCaptureService(downloader: PageResourceDownloader(), store: snapshotStore),
      snapshotStore: snapshotStore,
      localServer: LocalSnapshotServer(encryptor: snapshotEncryptor),
      handoffService: handoffService,
    );

    setState(() {
      _db = db;
      _syncEngine = syncEngine;
      _activationService = activationService;
      _revocationHandler = revocationHandler;
      _offlinePageCoordinator = offlinePageCoordinator;
      _configService = configService;
      _userSessionService = userSessionService;
    });
  }

  Future<String> _resolveOsVersion() async {
    final deviceInfo = DeviceInfoPlugin();
    if (Platform.isAndroid) {
      final info = await deviceInfo.androidInfo;
      return 'Android ${info.version.release}';
    } else if (Platform.isIOS) {
      final info = await deviceInfo.iosInfo;
      return 'iOS ${info.systemVersion}';
    }
    return Platform.operatingSystem;
  }

  void _onActivated() => setState(() => _isActivated = true);

  /// Called by HomeScreen AFTER RevocationHandler.handle() already closed
  /// the old AppDatabase and deleted its file + encryption key (review
  /// round 2, point 2). Nulling the service fields out immediately means
  /// `build()`'s `ready` check goes false and shows the loading spinner
  /// rather than an ActivationScreen briefly wired to now-closed services,
  /// while a fresh database (and fresh key) is opened underneath.
  void _onRevoked() {
    setState(() {
      _isActivated = false;
      _db = null;
      _syncEngine = null;
      _activationService = null;
      _revocationHandler = null;
      _offlinePageCoordinator = null;
      _configService = null;
      _userSessionService = null;
    });
    _openFreshDatabaseAndWireServices();
  }

  @override
  Widget build(BuildContext context) {
    final ready = _isActivated != null &&
        _db != null &&
        _syncEngine != null &&
        _activationService != null &&
        _revocationHandler != null &&
        _configService != null &&
        _userSessionService != null &&
        _offlinePageCoordinator != null;

    return MaterialApp(
      title: 'Ministrant Manager',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: const Color(0xFF1C2B4A)),
      home: !ready
          ? const Scaffold(body: Center(child: CircularProgressIndicator()))
          // Review round 2, point 5: global client-config (maintenance
          // mode / forced update) is checked HERE, in front of BOTH
          // HomeScreen and ActivationScreen — not only after activation.
          // See PreflightGate's own docblock for the exact ordering.
          : PreflightGate(
              configService: _configService!,
              appVersion: _appVersion,
              child: _isActivated!
                  ? HomeScreen(
                      db: _db!,
                      syncEngine: _syncEngine!,
                      configService: _configService!,
                      revocationHandler: _revocationHandler!,
                      userSessionService: _userSessionService!,
                      offlinePageCoordinator: _offlinePageCoordinator!,
                      onRevoked: _onRevoked,
                      appVersion: _appVersion,
                      osVersion: _osVersion,
                    )
                  : ActivationScreen(
                      key: ValueKey(_pendingDeepLinkToken),
                      activationService: _activationService!,
                      onActivated: _onActivated,
                      initialToken: _pendingDeepLinkToken,
                    ),
            ),
    );
  }
}
